/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entities.Administrateur;
import Entities.Candidat;
import Entities.Gerant_Entreprise;
import Entities_DAO.Administrateur_DAO;
import Entities_DAO.Candidat_DAO;
import Entities_DAO.Gerant_Entreprise_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ibrahim
 */
public class Authentication extends javax.swing.JFrame {

    private String Login = "";
    private String Password = "";
    private Administrateur admini;
    private Candidat cand;
    private Gerant_Entreprise gerant;
    private int result = 0;
    FramePrincipale f ;

    public int getResult() {
        return result;
    }

    public Administrateur getAdmini() {
        return admini;
    }   
    public Authentication() {
        initComponents();
        
    }

    public Authentication( FramePrincipale f) {
        this.f = f;
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFiledLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFiledPassword = new javax.swing.JPasswordField();
        Se_connecter = new javax.swing.JButton();
        Authentification_Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 108, 197));
        jLabel1.setText("Authentication");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN :");

        TextFiledLogin.setName("TextFiledLogin"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("PASSWORD : ");

        TextFiledPassword.setName("TextFiledPassword"); // NOI18N

        Se_connecter.setText("Se connecter");
        Se_connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Se_connecterActionPerformed(evt);
            }
        });

        Authentification_Annuler.setText("Annuler");
        Authentification_Annuler.setMaximumSize(new java.awt.Dimension(95, 23));
        Authentification_Annuler.setMinimumSize(new java.awt.Dimension(95, 23));
        Authentification_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Authentification_AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFiledLogin)
                            .addComponent(TextFiledPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Se_connecter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Authentification_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFiledLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFiledPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Se_connecter)
                    .addComponent(Authentification_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Se_connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Se_connecterActionPerformed

        Login = TextFiledLogin.getText().toString();
        Password = new String(TextFiledPassword.getPassword()); 
        //System.out.println(Login);
        //System.out.println(Password);
        if ((TextFiledLogin.getText().isEmpty()) && (Password.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Les ne doit pas etre vide ", "Erreur d'accès", JOptionPane.ERROR_MESSAGE);
            
        } else {
            result = Se_Authentifier(Login, Password);
            TextFiledLogin.setText("");
            TextFiledPassword.setText("");
        if(result==1)
        {
                Reponseauthentification r= new Reponseauthentification();
                r.setVisible(true);
                r.setReponse("Bonjour MR/MME "+admini.getNom_Administrateur()); 
                dispose();
                f.dispose();
                
        }
        if(result==2)
        {
                Reponseauthentification r= new Reponseauthentification();
                r.setVisible(true);
                r.setReponse("Bonjour MR/MME "+cand.getNom_Candidat()); 
                dispose();
                f.dispose();
                
        }
         if(result==3)
        {
                Reponseauthentification r= new Reponseauthentification();
                r.setVisible(true);
                r.setReponse("Bonjour MR/MME "+gerant.getNom_Gerant_Entreprise()); 
                dispose();
                f.dispose();
                
        }
        if(result==-1)
        {
              Reponseauthentification r= new Reponseauthentification();
                r.setVisible(true);
                r.setReponse("vous n'éte pas inscri vous pouvez s'inscrire gratuitement");
        }

        }
    }//GEN-LAST:event_Se_connecterActionPerformed
    private int Se_Authentifier(String log, String pass) {
       //administrateur
        Administrateur_DAO admin = new Administrateur_DAO();
        admini = admin.Find_AdminByLogin_Password(log, pass);
       // candidat 
        Candidat_DAO candidat = new Candidat_DAO();
        cand = candidat.Find_CandidatByLogin_Password(log, pass);
        //gerant entreprise
        Gerant_Entreprise_DAO gerant_en = new Gerant_Entreprise_DAO();
        gerant = gerant_en.Find_Gerant_EntrepriseByLogin_Password(log, pass);
        //test s'il est un administrateur
        if ((admini.getLogin_Administrateur() != null && admini.getLogin_Administrateur().equals(log)) && (admini.getPassword_Administrateur() != null && admini.getPassword_Administrateur().equals(pass))) {
            result = 1;
        }
        //test s'il est un candidat
        if ((cand.getLogin_Candidat()!= null && cand.getLogin_Candidat().equals(log)) && (cand.getPassword_Candidat()!= null && cand.getPassword_Candidat().equals(pass))) {
            result = 2;
        }
        //test s'il est un gerant d'entreprise
        if ((gerant.getLogin_Gerant_Entreprise()!= null && gerant.getLogin_Gerant_Entreprise().equals(log)) && (gerant.getPassword_Gerant_Entreprise()!= null && gerant.getPassword_Gerant_Entreprise().equals(pass))) {
            result = 3;
        }
        else
        {
            result = -1;
        }   
        return result;
    }


    private void Authentification_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Authentification_AnnulerActionPerformed
        this.TextFiledLogin.setText(null);
        this.TextFiledPassword.setText(null);
        this.dispose();
    }//GEN-LAST:event_Authentification_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentication.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Authentification_Annuler;
    private javax.swing.JButton Se_connecter;
    private javax.swing.JTextField TextFiledLogin;
    private javax.swing.JPasswordField TextFiledPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
